### PR TITLE
Shiva

### PR DESCRIPTION
**Pull request by ShivaPouladzadeh**
Changes in user interfaces of "faps-custom-app"

### CODE REVIEW

**Comment by davidcann** [comment]
What's this?

**Comment by ShivaPouladzadeh** [comment]
Hello, I have added the modified "standby-screen" and "accessory-page" pages.

**Comment by ShivaPouladzadeh** [comment]
> Hello, I have added the modified "standby-screen" and "accessory-page" pages.

**Comment by ShivaPouladzadeh** [comment]
> What's this?
Hello, I have added the modified "standby-screen" and "accessory-page" pages.

**Comment by simon-dengler** [comment]
Seems like the wrong target branch. It should be simon-dengler:master

**Pull request closed without merging**
